// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:pot_g/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ApiChannelAdapter());
    registerAdapter(ApiChannelSettingsAdapter());
    registerAdapter(HiddenMenuLevelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ApiChannelAdapter());
    registerAdapter(ApiChannelSettingsAdapter());
    registerAdapter(HiddenMenuLevelAdapter());
  }
}
